// Generated by npm run images:dimensions. Do not edit by hand.
export const GENERATED_IMAGE_DIMENSIONS = {
  "assets/brand/aditya-gollapudi-wordmark-hero.svg": [
    971,
    546
  ],
  "assets/brand/aditya-gollapudi-wordmark.svg": [
    971,
    546
  ],
  "assets/brand/aditya-mark-white.svg": [
    367,
    335
  ],
  "assets/brand/aditya-mark.svg": [
    367,
    335
  ],
  "assets/images/arc/arc-component-map.png": [
    1920,
    1080
  ],
  "assets/images/arc/arc-journey-01.png": [
    788,
    531
  ],
  "assets/images/arc/arc-journey-02.png": [
    1048,
    531
  ],
  "assets/images/arc/arc-journey-03.png": [
    1090,
    540
  ],
  "assets/images/arc/arc-journey-04.png": [
    746,
    540
  ],
  "assets/images/arc/arc-materials-finish-01.png": [
    1920,
    1080
  ],
  "assets/images/arc/arc-materials-finish-02.png": [
    1920,
    1080
  ],
  "assets/images/arc/arc-model-one-01.png": [
    536,
    540
  ],
  "assets/images/arc/arc-model-one-02.png": [
    536,
    540
  ],
  "assets/images/arc/arc-model-one-03.png": [
    536,
    540
  ],
  "assets/images/arc/arc-model-one-04.png": [
    536,
    540
  ],
  "assets/images/arc/arc-model-two-01.png": [
    463,
    824
  ],
  "assets/images/arc/arc-model-two-02.png": [
    463,
    824
  ],
  "assets/images/arc/arc-model-two-03.png": [
    463,
    824
  ],
  "assets/images/arc/arc-model-two-04.png": [
    463,
    824
  ],
  "assets/images/arc/arc-model-two-05.png": [
    454,
    807
  ],
  "assets/images/arc/arc-model-two-06.png": [
    454,
    807
  ],
  "assets/images/arc/arc-model-two-07.png": [
    454,
    807
  ],
  "assets/images/arc/arc-model-two-08.png": [
    454,
    807
  ],
  "assets/images/arc/arc-price-positioning.png": [
    1075,
    994
  ],
  "assets/images/arc/arc-sketch-01.png": [
    385,
    249
  ],
  "assets/images/arc/arc-sketch-02.png": [
    382,
    251
  ],
  "assets/images/arc/arc-sketch-03.png": [
    378,
    249
  ],
  "assets/images/arc/arc-sketch-04.png": [
    388,
    247
  ],
  "assets/images/arc/arc-sketch-05.png": [
    386,
    249
  ],
  "assets/images/arc/arc-sketch-06.png": [
    386,
    249
  ],
  "assets/images/arc/arc-sketch-07.png": [
    382,
    259
  ],
  "assets/images/arc/arc-sketch-08.png": [
    383,
    261
  ],
  "assets/images/arc/arc-sketch-09.png": [
    386,
    261
  ],
  "assets/images/arc/arc-sketch-10.png": [
    383,
    261
  ],
  "assets/images/arc/arc-sketch-11.png": [
    390,
    261
  ],
  "assets/images/arc/arc-sketch-12.png": [
    390,
    249
  ],
  "assets/images/arc/arc-sketch-13.png": [
    386,
    249
  ],
  "assets/images/arc/arc-sketch-14.png": [
    382,
    248
  ],
  "assets/images/arc/arc-sketch-15.png": [
    383,
    250
  ],
  "assets/images/arc/arc-sketch-16.png": [
    620,
    368
  ],
  "assets/images/arc/arc-sketch-17.png": [
    563,
    475
  ],
  "assets/images/arc/arc-sketch-18.png": [
    529,
    476
  ],
  "assets/images/arc/arc-sketch-19.png": [
    616,
    476
  ],
  "assets/images/arc/arc-sketch-20.png": [
    585,
    438
  ],
  "assets/images/arc/COFFEE.51.1.jpg": [
    1920,
    1255
  ],
  "assets/images/arc/COFFEE1.52.jpg": [
    2199,
    1438
  ],
  "assets/images/arc/COFFEE1.54.jpg": [
    1920,
    1255
  ],
  "assets/images/arc/COFFEE1.57.jpg": [
    1920,
    1273
  ],
  "assets/images/arc/COFFEE1.59.jpg": [
    1920,
    1255
  ],
  "assets/images/arc/COFFEE1.66 1.jpg": [
    1920,
    1255
  ],
  "assets/images/arc/Slide 16_9 - 95.jpg": [
    1920,
    1080
  ],
  "assets/images/arc/Slide 16_9 - 96.jpg": [
    1920,
    1080
  ],
  "assets/images/arc/Slide 16_9 - 97.jpg": [
    1920,
    1080
  ],
  "assets/images/arc/untitled.46.jpg": [
    1920,
    1255
  ],
  "assets/images/arc/untitled.47.jpg": [
    1946,
    1272
  ],
  "assets/images/arc/untitled.49.1.jpg": [
    1946,
    1272
  ],
  "assets/images/arc/Untitled.jpg": [
    1920,
    1080
  ],
  "assets/images/arc/WhatsApp Image 2025-11-12 at 00.06.58_3ccbb2c6 1.jpg": [
    1966,
    1264
  ],
  "assets/images/aurio/Container.svg": [
    1018,
    1018
  ],
  "assets/images/aurio/image 10.jpg": [
    1705,
    2274
  ],
  "assets/images/aurio/image 19.jpg": [
    1707,
    2276
  ],
  "assets/images/aurio/image 20.jpg": [
    2074,
    986
  ],
  "assets/images/aurio/image 21.jpg": [
    1425,
    1432
  ],
  "assets/images/aurio/image 22.jpg": [
    1425,
    1432
  ],
  "assets/images/aurio/image 23.jpg": [
    1670,
    2226
  ],
  "assets/images/aurio/image 24.jpg": [
    1669,
    2226
  ],
  "assets/images/aurio/image 4.jpg": [
    4060,
    1695
  ],
  "assets/images/aurio/image 5.jpg": [
    1774,
    1583
  ],
  "assets/images/aurio/image 57.jpg": [
    1276,
    1701
  ],
  "assets/images/aurio/image 58.jpg": [
    2267,
    1700
  ],
  "assets/images/aurio/image 59.jpg": [
    2267,
    1700
  ],
  "assets/images/aurio/image 6.jpg": [
    2419,
    1612
  ],
  "assets/images/aurio/image 60.jpg": [
    1062,
    1416
  ],
  "assets/images/aurio/image 61.jpg": [
    1064,
    1418
  ],
  "assets/images/aurio/image 62.jpg": [
    1063,
    1418
  ],
  "assets/images/aurio/image 63.jpg": [
    1064,
    1418
  ],
  "assets/images/aurio/image 64.jpg": [
    1063,
    1418
  ],
  "assets/images/aurio/image 7.jpg": [
    1707,
    2276
  ],
  "assets/images/aurio/image 72.jpg": [
    1822,
    2429
  ],
  "assets/images/aurio/image 73.jpg": [
    1822,
    2429
  ],
  "assets/images/aurio/image 74.jpg": [
    1822,
    2429
  ],
  "assets/images/aurio/image 8.jpg": [
    1706,
    2274
  ],
  "assets/images/aurio/Slide 16_9 - 82.png": [
    1920,
    1080
  ],
  "assets/images/aurio/Slide 16_9 - 83.png": [
    1920,
    1080
  ],
  "assets/images/aurio/Slide 16_9 - 84 2.png": [
    1920,
    1080
  ],
  "assets/images/aurio/Slide 16_9 - 84 3.jpg": [
    1920,
    1080
  ],
  "assets/images/aurio/Slide 16_9 - 85 2.png": [
    1920,
    1080
  ],
  "assets/images/aurio/Slide 16_9 - 85 3.jpg": [
    1920,
    1080
  ],
  "assets/images/aurio/Untitled (1) 1.jpg": [
    1920,
    1080
  ],
  "assets/images/aurio/Untitled2 2.jpg": [
    1920,
    1080
  ],
  "assets/images/aurio/Untitled4 2.jpg": [
    1920,
    1080
  ],
  "assets/images/aurio/Untitled6 (1) 1.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/25.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/26.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/27.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/28.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/29.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/30.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/31.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/32.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/33.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/Group 133.jpg": [
    3255,
    1022
  ],
  "assets/images/bastion/mobile-delivery-alert.jpg": [
    440,
    956
  ],
  "assets/images/bastion/mobile-event-feed.jpg": [
    440,
    956
  ],
  "assets/images/bastion/mobile-lock-control.jpg": [
    440,
    956
  ],
  "assets/images/bastion/mobile-wallet-card.jpg": [
    440,
    956
  ],
  "assets/images/bastion/new 1.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/new 17 1.jpg": [
    899,
    1078
  ],
  "assets/images/bastion/new1 1.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/new6 1.jpg": [
    1920,
    1080
  ],
  "assets/images/bastion/WhatsApp Image 2025-03-13 at 17.20.18_441121a4 1.jpg": [
    1790,
    2856
  ],
  "assets/images/bastion/WhatsApp Image 2025-03-14 at 18.00.27_97664882 1.jpg": [
    2198,
    1719
  ],
  "assets/images/bastion/WhatsApp Image 2025-03-14 at 18.06.50_7a1c2941 1.jpg": [
    1100,
    1735
  ],
  "assets/images/bastion/WhatsApp Image 2025-04-28 at 23.23.31_24948770 1.jpg": [
    1328,
    1442
  ],
  "assets/images/bastion/WhatsApp Image 2025-05-05 at 20.08.02_f8660830 1.jpg": [
    801,
    1423
  ],
  "assets/images/bastion/WhatsApp Image 2025-05-05 at 20.08.15_35839a96 1.jpg": [
    877,
    1422
  ],
  "assets/images/bastion/WhatsApp Image 2025-05-05 at 20.08.35_1c47a6c7 1.jpg": [
    1155,
    1423
  ],
  "assets/images/cura/After.png": [
    420,
    867
  ],
  "assets/images/cura/Before.png": [
    419,
    867
  ],
  "assets/images/cura/cura-device-hero.jpg": [
    2400,
    800
  ],
  "assets/images/cura/Group 153.png": [
    450,
    920
  ],
  "assets/images/cura/Group 154.png": [
    450,
    920
  ],
  "assets/images/cura/Group 155.png": [
    450,
    920
  ],
  "assets/images/cura/Group 156.png": [
    450,
    920
  ],
  "assets/images/cura/Group 157.png": [
    450,
    920
  ],
  "assets/images/cura/Group 158.png": [
    450,
    920
  ],
  "assets/images/cura/Group 159.png": [
    450,
    920
  ],
  "assets/images/cura/Group 160.png": [
    450,
    920
  ],
  "assets/images/cura/Group 161.png": [
    450,
    920
  ],
  "assets/images/cura/Group 162.png": [
    450,
    920
  ],
  "assets/images/cura/Group 163.png": [
    450,
    920
  ],
  "assets/images/cura/Group 164.png": [
    450,
    920
  ],
  "assets/images/cura/Hand and iPhone 16 Pro-!.png": [
    740,
    540
  ],
  "assets/images/cura/Hand and iPhone 16 Pro.png": [
    1500,
    1125
  ],
  "assets/images/cura/iPhone 16 Pro - 46.png": [
    166,
    399
  ],
  "assets/images/cura/iPhone 16 Pro - 47.png": [
    166,
    372
  ],
  "assets/images/cura/iPhone 16 Pro - 48.png": [
    402,
    876
  ],
  "assets/images/cura/iPhone 16 Pro - 49.png": [
    402,
    874
  ],
  "assets/images/cura/iPhone 16 Pro - 50.png": [
    402,
    876
  ],
  "assets/images/cura/iPhone 16 Pro - 51.png": [
    402,
    1150
  ],
  "assets/images/cura/iPhone 16 Pro - 58.png": [
    166,
    361
  ],
  "assets/images/cura/iPhone 16 Pro - 59.png": [
    166,
    361
  ],
  "assets/images/cura/iPhone 16 Pro - 61.png": [
    166,
    490
  ],
  "assets/images/cura/iPhone 16 Pro - 62.png": [
    166,
    470
  ],
  "assets/images/cura/iPhone 16 Pro - 63.png": [
    166,
    372
  ],
  "assets/images/cura/iPhone 16 Pro - 64.png": [
    166,
    361
  ],
  "assets/images/cura/iPhone 16 Pro - 65.png": [
    166,
    351
  ],
  "assets/images/cura/iPhone 16 Pro.png": [
    1500,
    1125
  ],
  "assets/images/cura/Notification 1.png": [
    166,
    361
  ],
  "assets/images/cura/Slide 16_9 - 2.png": [
    1920,
    1080
  ],
  "assets/images/forkast/01-wireframe-menu.png": [
    924,
    1954
  ],
  "assets/images/forkast/02-wireframe-dish.png": [
    924,
    1954
  ],
  "assets/images/forkast/03-wireframe-dashboard.png": [
    924,
    578
  ],
  "assets/images/forkast/04-wireframe-dashboard-2.png": [
    924,
    578
  ],
  "assets/images/forkast/05-set-allergens.png": [
    924,
    1954
  ],
  "assets/images/forkast/06-menu-safe.png": [
    924,
    3172
  ],
  "assets/images/forkast/07-dish-safe.png": [
    924,
    2466
  ],
  "assets/images/forkast/08-dish-caution.png": [
    924,
    2887
  ],
  "assets/images/forkast/09-empty-state.png": [
    924,
    2009
  ],
  "assets/images/forkast/12-server-section.png": [
    924,
    578
  ],
  "assets/images/forkast/13-kitchen-line-display.png": [
    924,
    578
  ],
  "assets/images/forkast/14-chef-escalations.png": [
    924,
    578
  ],
  "assets/images/forkast/15-system-overview.png": [
    924,
    635
  ],
  "assets/images/forkast/showcase/ask-question.png": [
    450,
    920
  ],
  "assets/images/forkast/showcase/avoid-dish.png": [
    450,
    920
  ],
  "assets/images/forkast/showcase/avoid-substitution.png": [
    450,
    920
  ],
  "assets/images/forkast/showcase/caution-dish.png": [
    450,
    920
  ],
  "assets/images/forkast/showcase/caution-substitution.png": [
    450,
    920
  ],
  "assets/images/forkast/showcase/chef-dish-editor.png": [
    1320,
    940
  ],
  "assets/images/forkast/showcase/chef-escalations.png": [
    1500,
    1150
  ],
  "assets/images/forkast/showcase/customer-safety-composition.png": [
    5550,
    3000
  ],
  "assets/images/forkast/showcase/device-composition.png": [
    4000,
    3000
  ],
  "assets/images/forkast/showcase/forkast-allergy-hero.jpg": [
    2400,
    883
  ],
  "assets/images/forkast/showcase/kitchen-line.png": [
    1320,
    940
  ],
  "assets/images/forkast/showcase/menu-in-hand-blue.png": [
    1500,
    1125
  ],
  "assets/images/forkast/showcase/menu-in-hand-grey.png": [
    1500,
    1125
  ],
  "assets/images/forkast/showcase/no-safe-options.png": [
    450,
    920
  ],
  "assets/images/forkast/showcase/safe-dish.png": [
    450,
    920
  ],
  "assets/images/forkast/showcase/safe-menu.png": [
    450,
    920
  ],
  "assets/images/forkast/showcase/waiter-dashboard.png": [
    1500,
    1150
  ],
  "assets/images/personal/barcelona.webp": [
    570,
    554
  ],
  "assets/images/personal/blender-logo.png": [
    512,
    512
  ],
  "assets/images/personal/camera.webp": [
    738,
    656
  ],
  "assets/images/personal/camp-nou.webp": [
    552,
    337
  ],
  "assets/images/personal/ferrari-f1.webp": [
    1361,
    548
  ],
  "assets/images/personal/filter-coffee.webp": [
    865,
    816
  ],
  "assets/images/personal/football-ball.png": [
    1254,
    1254
  ],
  "assets/images/personal/football-boot.webp": [
    760,
    425
  ],
  "assets/images/personal/gallery/blender-blue-porsche-render.jpg": [
    1280,
    720
  ],
  "assets/images/personal/gallery/blender-caterham-render.jpg": [
    1600,
    900
  ],
  "assets/images/personal/gallery/blender-concept-side-render.jpg": [
    823,
    1600
  ],
  "assets/images/personal/gallery/blender-concept-top-render.jpg": [
    823,
    1600
  ],
  "assets/images/personal/gallery/blender-mercedes-render.jpg": [
    1600,
    900
  ],
  "assets/images/personal/gallery/blender-work-in-progress.jpg": [
    1200,
    1600
  ],
  "assets/images/personal/gallery/filter-kaapi.jpg": [
    2400,
    1600
  ],
  "assets/images/personal/gallery/football-playing.jpg": [
    2400,
    1600
  ],
  "assets/images/personal/gallery/machines-engine-bay.jpg": [
    1600,
    1200
  ],
  "assets/images/personal/gallery/machines-indy-car.jpg": [
    1200,
    1600
  ],
  "assets/images/personal/gallery/machines-porsche-night.jpg": [
    1200,
    1600
  ],
  "assets/images/personal/gallery/machines-triumph-bobber.jpg": [
    587,
    522
  ],
  "assets/images/personal/gallery/photography-cleveland-tower.jpg": [
    1200,
    1600
  ],
  "assets/images/personal/gallery/photography-kansas-city-station.jpg": [
    1200,
    1600
  ],
  "assets/images/personal/gallery/photography-mountain-landscape.jpg": [
    2400,
    1600
  ],
  "assets/images/personal/gallery/photography-qutub-minar.jpg": [
    1200,
    1600
  ],
  "assets/images/personal/gallery/photography-red-fort.jpg": [
    1600,
    1200
  ],
  "assets/images/personal/gallery/photography-sky-plane.jpg": [
    1200,
    1600
  ],
  "assets/images/personal/hampi.webp": [
    390,
    340
  ],
  "assets/images/personal/motorcycle-engine.png": [
    1254,
    1254
  ],
  "assets/images/personal/porsche.webp": [
    848,
    1055
  ],
  "assets/images/personal/stone-detail.png": [
    1254,
    1254
  ],
  "assets/images/personal/triumph.webp": [
    749,
    688
  ],
  "assets/images/personal/world-cup.webp": [
    578,
    1127
  ],
  "assets/images/research/arc-morning-ritual.jpg": [
    1800,
    2400
  ],
  "assets/images/research/arc-sculptural-interior.jpg": [
    1800,
    2916
  ],
  "assets/images/research/aurio-social-listening.jpg": [
    1800,
    1200
  ],
  "assets/images/research/forkast-diner-waiter.jpg": [
    1800,
    1200
  ],
  "assets/images/research/forkast-kitchen-team.jpg": [
    1799,
    1200
  ],
  "assets/images/web-projects/responsive/sanathan-sethu-macbook-1280.webp": [
    1280,
    960
  ],
  "assets/images/web-projects/responsive/sanathan-sethu-macbook-1920.webp": [
    1920,
    1440
  ],
  "assets/images/web-projects/responsive/sanathan-sethu-macbook-768.webp": [
    768,
    576
  ],
  "assets/images/web-projects/responsive/seeker-social-macbook-1280.webp": [
    1280,
    960
  ],
  "assets/images/web-projects/responsive/seeker-social-macbook-1920.webp": [
    1920,
    1440
  ],
  "assets/images/web-projects/responsive/seeker-social-macbook-768.webp": [
    768,
    576
  ],
  "assets/images/web-projects/responsive/vaijayanthy-macbook-1280.webp": [
    1280,
    960
  ],
  "assets/images/web-projects/responsive/vaijayanthy-macbook-1920.webp": [
    1920,
    1440
  ],
  "assets/images/web-projects/responsive/vaijayanthy-macbook-768.webp": [
    768,
    576
  ],
  "assets/images/web-projects/responsive/world-clock-macbook-1280.webp": [
    1280,
    720
  ],
  "assets/images/web-projects/responsive/world-clock-macbook-1920.webp": [
    1920,
    1080
  ],
  "assets/images/web-projects/responsive/world-clock-macbook-768.webp": [
    768,
    432
  ],
  "assets/images/web-projects/sanathan-sethu-macbook.png": [
    4000,
    3000
  ],
  "assets/images/web-projects/seeker-social-macbook.png": [
    4000,
    3000
  ],
  "assets/images/web-projects/vaijayanthy-macbook.png": [
    4000,
    3000
  ],
  "assets/images/web-projects/world-clock-macbook.png": [
    1920,
    1080
  ]
}
